package pdf

import (
	"bytes"
	"fmt"
	"time"

	"github.com/go-pdf/fpdf"
)

type InvoicePDFData struct {
	InvoiceNumber   string
	InvoiceDate     string
	DealerName      string
	DealerAddress   string
	DealerGSTIN     string
	CustomerName    string
	CustomerPhone   string
	CustomerAddress string
	ProductName     string
	ModelNumber     string
	SerialNumber    string
	TaxableAmount   float64
	GSTPercentage   float64
	CGSTAmount      float64
	SGSTAmount      float64
	TotalAmount     float64
	WarrantyEndDate string
}

func GenerateInvoicePDF(data InvoicePDFData) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.AddPage()

	// Title
	pdf.SetFont("Arial", "B", 18)
	pdf.CellFormat(180, 12, "TAX INVOICE", "", 1, "C", false, 0, "")
	pdf.Ln(4)

	// Invoice info line
	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(90, 6, fmt.Sprintf("Invoice No: %s", data.InvoiceNumber), "", 0, "L", false, 0, "")
	invoiceDate := data.InvoiceDate
	if invoiceDate == "" {
		invoiceDate = time.Now().Format("2006-01-02")
	}
	pdf.CellFormat(90, 6, fmt.Sprintf("Date: %s", invoiceDate), "", 1, "R", false, 0, "")
	pdf.Ln(6)

	// Separator
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(6)

	// Seller / Buyer columns
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(90, 6, "Seller Details", "", 0, "L", false, 0, "")
	pdf.CellFormat(90, 6, "Buyer Details", "", 1, "L", false, 0, "")

	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(90, 5, data.DealerName, "", 0, "L", false, 0, "")
	pdf.CellFormat(90, 5, data.CustomerName, "", 1, "L", false, 0, "")

	pdf.CellFormat(90, 5, data.DealerAddress, "", 0, "L", false, 0, "")
	pdf.CellFormat(90, 5, data.CustomerPhone, "", 1, "L", false, 0, "")

	if data.DealerGSTIN != "" {
		pdf.CellFormat(90, 5, fmt.Sprintf("GSTIN: %s", data.DealerGSTIN), "", 0, "L", false, 0, "")
	} else {
		pdf.CellFormat(90, 5, "", "", 0, "L", false, 0, "")
	}
	pdf.CellFormat(90, 5, data.CustomerAddress, "", 1, "L", false, 0, "")
	pdf.Ln(8)

	// Product table header
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(2)

	pdf.SetFont("Arial", "B", 10)
	pdf.SetFillColor(240, 240, 240)
	pdf.CellFormat(10, 8, "#", "1", 0, "C", true, 0, "")
	pdf.CellFormat(60, 8, "Product", "1", 0, "L", true, 0, "")
	pdf.CellFormat(40, 8, "Model", "1", 0, "L", true, 0, "")
	pdf.CellFormat(40, 8, "Serial No.", "1", 0, "L", true, 0, "")
	pdf.CellFormat(30, 8, "Amount", "1", 1, "R", true, 0, "")

	// Product row
	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(10, 8, "1", "1", 0, "C", false, 0, "")
	pdf.CellFormat(60, 8, truncate(data.ProductName, 30), "1", 0, "L", false, 0, "")
	pdf.CellFormat(40, 8, truncate(data.ModelNumber, 20), "1", 0, "L", false, 0, "")
	pdf.CellFormat(40, 8, truncate(data.SerialNumber, 20), "1", 0, "L", false, 0, "")
	pdf.CellFormat(30, 8, fmt.Sprintf("%.2f", data.TaxableAmount), "1", 1, "R", false, 0, "")
	pdf.Ln(6)

	// Tax breakdown
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(180, 7, "Tax Breakdown", "", 1, "L", false, 0, "")

	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(130, 6, "Taxable Amount", "", 0, "L", false, 0, "")
	pdf.CellFormat(50, 6, fmt.Sprintf("Rs. %.2f", data.TaxableAmount), "", 1, "R", false, 0, "")

	pdf.CellFormat(130, 6, fmt.Sprintf("CGST @ %.1f%%", data.GSTPercentage/2), "", 0, "L", false, 0, "")
	pdf.CellFormat(50, 6, fmt.Sprintf("Rs. %.2f", data.CGSTAmount), "", 1, "R", false, 0, "")

	pdf.CellFormat(130, 6, fmt.Sprintf("SGST @ %.1f%%", data.GSTPercentage/2), "", 0, "L", false, 0, "")
	pdf.CellFormat(50, 6, fmt.Sprintf("Rs. %.2f", data.SGSTAmount), "", 1, "R", false, 0, "")

	pdf.Ln(2)
	pdf.SetDrawColor(0, 0, 0)
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(2)

	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(130, 8, "Total Amount", "", 0, "L", false, 0, "")
	pdf.CellFormat(50, 8, fmt.Sprintf("Rs. %.2f", data.TotalAmount), "", 1, "R", false, 0, "")
	pdf.Ln(10)

	// Warranty note
	if data.WarrantyEndDate != "" {
		pdf.SetFont("Arial", "I", 9)
		pdf.CellFormat(180, 5, fmt.Sprintf("Warranty valid until: %s", data.WarrantyEndDate), "", 1, "L", false, 0, "")
	}

	// Footer
	pdf.Ln(10)
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(128, 128, 128)
	pdf.CellFormat(180, 4, "This is a computer-generated invoice and does not require a signature.", "", 1, "C", false, 0, "")
	pdf.CellFormat(180, 4, "Generated by Warrantly - Warranty Management Platform", "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
